branches: {only: [master, test]}
environment:
  matrix:
    - TOXENV: py27-pip8.1.1
    - TOXENV: py27-piplatest
    - TOXENV: py34-pip8.1.1
    - TOXENV: py34-piplatest
    - TOXENV: py35-piplatest
    - TOXENV: py36-piplatest
install:
  - pip install -U pip setuptools wheel
  - pip install codecov
  - pip install -U tox
build_script:
  - python setup.py bdist_wheel
test_script:
  - 'FOR %%w IN ("dist\*.whl") DO tox -v --installpkg "%%w"'
cache:
  - '%LocalAppData%\pip\cache'
after_test:
  - codecov
