sudo: false
language: python

env:
  - TOXENV=flake8
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-piplatest
    - python: 3.4
      env: TOXENV=py34-piplatest
    - python: 3.5
      env: TOXENV=py35-piplatest
    - python: 2.7
      env: TOXENV=py27-pip8
    - python: 3.4
      env: TOXENV=py34-pip8
    - python: 3.5
      env: TOXENV=py35-pip8
    - python: 2.7
      env: TOXENV=py27-pip9
    - python: 3.4
      env: TOXENV=py34-pip9
    - python: 3.5
      env: TOXENV=py35-pip9

install:
  - travis_retry pip install tox
  - travis_retry pip install codecov
  - travis_retry pip install coveralls
  - pip install -U pip setuptools
  - python setup.py bdist_wheel

cache: pip

script: tox -v --installpkg dist/*.whl

after_success:
  - codecov
  - coveralls
