branches: {only: [master]}

sudo: false
language: python
cache: pip

matrix:
  include:
    - {env: TOXENV=style, python: "3.4"}
    - {env: TOXENV=packaging, python: "3.4"}
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

install:
  - pip install tox-travis
  - pip install codecov
  - pip install -U pip setuptools
  - python setup.py bdist_wheel

script: tox -v --installpkg dist/*.whl

after_success:
  - codecov -e TRAVIS_PYTHON_VERSION
